/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citybites.ui;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author User
 */
public class CustomerDashboardFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerDashboardFrame.class.getName());

    /**
     * Creates new form CustomerDashboardFrame
     */
    public CustomerDashboardFrame() {
        initComponents();
        setTitle("City Bites - Customer Dashboard");
        setSize(750, 550);
        setLocationRelativeTo(null);
        setResizable(false);

        citybites.model.Customer customer = citybites.util.SessionManager.getLoggedInCustomer();
        if (customer != null) {
            lblWelcome.setText("Welcome, " + customer.getFullName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle    = new javax.swing.JLabel();
        lblWelcome  = new javax.swing.JLabel();
        btnViewMenu  = new javax.swing.JButton();
        btnViewCart  = new javax.swing.JButton();
        btnLogout    = new javax.swing.JButton();
        btnMyOrders  = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // ── Labels ──────────────────────────────────────────────────────────────
        lblTitle.setText("CITY BITES");
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 26));
        lblTitle.setForeground(new Color(41, 128, 185));
        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitle.setAlignmentX(Component.CENTER_ALIGNMENT);

        lblWelcome.setText("Welcome");
        lblWelcome.setFont(new Font("Segoe UI", Font.BOLD, 16));
        lblWelcome.setForeground(new Color(44, 62, 80));
        lblWelcome.setHorizontalAlignment(SwingConstants.CENTER);
        lblWelcome.setAlignmentX(Component.CENTER_ALIGNMENT);

        // ── Buttons ─────────────────────────────────────────────────────────────
        Dimension btnSize = new Dimension(220, 40);
        Font btnFont = new Font("Segoe UI", Font.BOLD, 13);

        btnViewMenu.setText("View Food Menu");
        btnViewMenu.setFont(btnFont);
        btnViewMenu.setPreferredSize(btnSize);
        btnViewMenu.setMaximumSize(btnSize);
        btnViewMenu.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnViewMenu.addActionListener(this::btnViewMenuActionPerformed);

        btnMyOrders.setText("My Orders");
        btnMyOrders.setFont(btnFont);
        btnMyOrders.setPreferredSize(btnSize);
        btnMyOrders.setMaximumSize(btnSize);
        btnMyOrders.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnMyOrders.addActionListener(this::btnMyOrdersActionPerformed);

        btnViewCart.setText("View Cart");
        btnViewCart.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        btnViewCart.setPreferredSize(btnSize);
        btnViewCart.setMaximumSize(btnSize);
        btnViewCart.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnViewCart.addActionListener(this::btnViewCartActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        btnLogout.setPreferredSize(new Dimension(130, 33));
        btnLogout.setMaximumSize(new Dimension(130, 33));
        btnLogout.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        // ── Header Panel ────────────────────────────────────────────────────────
        JPanel headerPanel = new JPanel();
        headerPanel.setBackground(Color.WHITE);
        headerPanel.setLayout(new BoxLayout(headerPanel, BoxLayout.Y_AXIS));
        headerPanel.setBorder(BorderFactory.createEmptyBorder(35, 20, 25, 20));
        headerPanel.add(lblTitle);
        headerPanel.add(Box.createVerticalStrut(8));
        headerPanel.add(lblWelcome);

        // ── Buttons Panel ────────────────────────────────────────────────────────
        JPanel btnPanel = new JPanel();
        btnPanel.setBackground(Color.WHITE);
        btnPanel.setLayout(new BoxLayout(btnPanel, BoxLayout.Y_AXIS));
        btnPanel.setBorder(BorderFactory.createEmptyBorder(35, 20, 20, 20));
        btnPanel.add(btnViewMenu);
        btnPanel.add(Box.createVerticalStrut(18));
        btnPanel.add(btnMyOrders);
        btnPanel.add(Box.createVerticalStrut(18));
        btnPanel.add(btnViewCart);
        btnPanel.add(Box.createVerticalStrut(40));
        btnPanel.add(btnLogout);
        btnPanel.add(Box.createVerticalGlue());

        // ── Main Layout ─────────────────────────────────────────────────────────
        getContentPane().setBackground(Color.WHITE);
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(headerPanel, BorderLayout.NORTH);
        getContentPane().add(btnPanel, BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to logout?",
                "Confirm Logout",
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            citybites.util.SessionManager.logout();
            new CustomerLoginFrame().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMenuActionPerformed
        new FoodMenuFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewMenuActionPerformed

    private void btnViewCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCartActionPerformed
        new CartFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewCartActionPerformed

    private void btnMyOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyOrdersActionPerformed
        new CustomerOrdersFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMyOrdersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerDashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyOrders;
    private javax.swing.JButton btnViewCart;
    private javax.swing.JButton btnViewMenu;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
