/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package citybites.ui;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author User
 */
public class WelcomeFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WelcomeFrame.class.getName());

    /**
     * Creates new form WelcomeFrame
     */
    public WelcomeFrame() {
        initComponents();
        setTitle("City Bites - Welcome");
        setSize(750, 550);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // ── Labels ──────────────────────────────────────────────────────────────
        lblTitle.setText("CITY BITES");
        lblTitle.setFont(new Font("Segoe UI", Font.BOLD, 28));
        lblTitle.setForeground(new Color(41, 128, 185));
        lblTitle.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitle.setAlignmentX(Component.CENTER_ALIGNMENT);

        lblSubtitle.setText("Food Management System");
        lblSubtitle.setFont(new Font("Segoe UI", Font.BOLD, 17));
        lblSubtitle.setForeground(new Color(44, 62, 80));
        lblSubtitle.setHorizontalAlignment(SwingConstants.CENTER);
        lblSubtitle.setAlignmentX(Component.CENTER_ALIGNMENT);

        lblMessage.setText("Select your login type to continue");
        lblMessage.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblMessage.setForeground(new Color(120, 130, 140));
        lblMessage.setHorizontalAlignment(SwingConstants.CENTER);
        lblMessage.setAlignmentX(Component.CENTER_ALIGNMENT);

        // ── Buttons ─────────────────────────────────────────────────────────────
        btnAdmin.setText("Admin Login");
        btnAdmin.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btnAdmin.setPreferredSize(new Dimension(200, 38));
        btnAdmin.setMaximumSize(new Dimension(200, 38));
        btnAdmin.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnAdmin.addActionListener(this::btnAdminActionPerformed);

        btnCustomer.setText("Customer Login");
        btnCustomer.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btnCustomer.setPreferredSize(new Dimension(200, 38));
        btnCustomer.setMaximumSize(new Dimension(200, 38));
        btnCustomer.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnCustomer.addActionListener(this::btnCustomerActionPerformed);

        btnExit.setText("Exit");
        btnExit.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        btnExit.setPreferredSize(new Dimension(120, 32));
        btnExit.setMaximumSize(new Dimension(120, 32));
        btnExit.setAlignmentX(Component.CENTER_ALIGNMENT);
        btnExit.addActionListener(this::btnExitActionPerformed);

        // ── Layout ──────────────────────────────────────────────────────────────
        JPanel mainPanel = new JPanel();
        mainPanel.setBackground(Color.WHITE);
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

        mainPanel.add(Box.createVerticalStrut(65));
        mainPanel.add(lblTitle);
        mainPanel.add(Box.createVerticalStrut(10));
        mainPanel.add(lblSubtitle);
        mainPanel.add(Box.createVerticalStrut(50));
        mainPanel.add(lblMessage);
        mainPanel.add(Box.createVerticalStrut(42));
        mainPanel.add(btnAdmin);
        mainPanel.add(Box.createVerticalStrut(16));
        mainPanel.add(btnCustomer);
        mainPanel.add(Box.createVerticalStrut(30));
        mainPanel.add(btnExit);
        mainPanel.add(Box.createVerticalGlue());

        getContentPane().setBackground(Color.WHITE);
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(mainPanel, BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        new AdminLoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        new CustomerLoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int response = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to exit?",
                "Confirm Exit",
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new WelcomeFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
